<?php

use App\Consts\AppConst;

return [

    // ディレクトリ
    'file_dir' => [
        'chg_depo_info' => env('DIR_CSV_CHG_DEPO_INFO', '/home/humony/humony_data/depo_chg/'),
        'public_holiday' => env('DIR_PUBLIC_HOLIDAY_CSV', '/home/humony/inifile/'),
        'public_holiday_bk' => env('DIR_PUBLIC_HOLIDAY_CSV_BK', '/home/humony/inifile/syuku_bak/'),
    ],

    // ファイル名
    'file_name' => [
        'calendar' => 'CalenderConfirm',
        'lead_time' => 'LeadtimeAddress',
        'depo_item' => 'DepoItem',
        'depo_address' => 'DepoAddress',
        'default_list' => 'DefaultList',
        'irregular_list' => 'IrregularList',
        'chg_depo_info' => 'ChgDepoInfo',
        'public_holiday' => env('PUBLIC_HOLIDAY_CSV_NAME', 'syuku1.csv'),
    ],
    
    // C_L20
    'default_list' => [
        ['住所CD','addrcd',AppConst::TYPE_STR],
        ['JIS市区町村','jiscode',AppConst::TYPE_STR],
        ['郵便番号','zipcode',AppConst::TYPE_STR],
        ['都道府県CD','pref',AppConst::TYPE_STR],
        ['市区郡','siku',AppConst::TYPE_STR],
        ['町名','tyou',AppConst::TYPE_STR],
        ['デポ名','deponame1',AppConst::TYPE_STR],
        ['デポCD','depo_cd',AppConst::TYPE_STR],
        ['翌日時間指定','next_day_time_type',AppConst::TYPE_STR],
        ['エリア当日配送可否','tue_before_deadline_flg',AppConst::TYPE_STR],
        ['翌日配送締切時間1','next_day_time_deadline',AppConst::TYPE_STR],
        ['当日配送締切時間1','today_time_deadline1',AppConst::TYPE_STR],
        ['当日配送締切時間2','today_time_deadline2',AppConst::TYPE_STR],
        ['月曜前日締切','mon_before_deadline_flg',AppConst::TYPE_STR],
        ['月曜当日配送','mon_today_delivery_flg',AppConst::TYPE_STR],
        ['火曜前日締切','tue_before_deadline_flg',AppConst::TYPE_STR],
        ['火曜当日配送','tue_today_delivery_flg',AppConst::TYPE_STR],
        ['水曜前日締切','wed_before_deadline_flg',AppConst::TYPE_STR],
        ['水曜当日配送','wed_today_delivery_flg',AppConst::TYPE_STR],
        ['木曜前日締切','thu_before_deadline_flg',AppConst::TYPE_STR],
        ['木曜当日配送','thu_today_delivery_flg',AppConst::TYPE_STR],
        ['金曜前日締切','fri_before_deadline_flg',AppConst::TYPE_STR],
        ['金曜当日配送','fri_today_delivery_flg',AppConst::TYPE_STR],
        ['土曜前日締切','sat_before_deadline_flg',AppConst::TYPE_STR],
        ['土曜当日配送','sat_today_delivery_flg',AppConst::TYPE_STR],
        ['日曜前日締切','sun_before_deadline_flg',AppConst::TYPE_STR],
        ['日曜当日配送','sun_today_delivery_flg',AppConst::TYPE_STR],
        ['祝前前日締切','holi_before_deadline_flg',AppConst::TYPE_STR],
        ['祝前当日配送','holi_before_today_delivery_flg',AppConst::TYPE_STR],
        ['祝日前日締切','holi_deadline_flg',AppConst::TYPE_STR],
        ['祝日当日配送','holi_today_delivery_flg',AppConst::TYPE_STR],
        ['祝後前日締切','holi_after_deadline_flg',AppConst::TYPE_STR],
        ['祝後当日配送','holi_after_today_delivery_flg',AppConst::TYPE_STR],
        ['個人宅可否','private_home_flg',AppConst::TYPE_STR],
        ['慶弔区分','congratulation_kbn_flg',AppConst::TYPE_STR],
        ['振替先郵便デポ','transfer_post_depo_cd',AppConst::TYPE_STR],
        ['振替先郵便デポ名','deponame2',AppConst::TYPE_STR],
        ['デポリードタイム','depo_lead_time',AppConst::TYPE_STR],
    ],
    // C_L30
    'irregular_list' => [
        ['ID','irregular_id',AppConst::TYPE_STR],
        ['イレギュラー設定区分','irregular_type',AppConst::TYPE_STR],
        ['タイトル','title',AppConst::TYPE_STR],
        ['デポCD','depo_cd',AppConst::TYPE_STR],
        ['カテゴリ(大)','lcat_cd',AppConst::TYPE_STR],
        ['カテゴリ(中)','mcat_cd',AppConst::TYPE_STR],
        ['商品名','item_cd',AppConst::TYPE_STR],
        ['用途','c_use_name',AppConst::TYPE_STR],
        ['前日締切不可','is_before_deadline_undeliv',AppConst::TYPE_STR],
        ['当日配送不可','is_today_deadline_undeliv',AppConst::TYPE_STR],
        ['時間指定不可','is_time_select_undeliv',AppConst::TYPE_STR],
        ['時間指定','time_select',AppConst::TYPE_STR],
        ['個人宅不可','is_personal_delivery',AppConst::TYPE_STR],
        ['地域区分','is_area',AppConst::TYPE_STR],
        ['お届け日期間・曜日区分','delivery_date_type',AppConst::TYPE_STR],
        ['日付','delivery_date',AppConst::TYPE_STR],
        ['期間FROM','delivery_date_from',AppConst::TYPE_STR],
        ['期間TO','delivery_date_to',AppConst::TYPE_STR],
        ['月曜','delivery_mon',AppConst::TYPE_STR],
        ['火曜','delivery_tue',AppConst::TYPE_STR],
        ['水曜','delivery_web',AppConst::TYPE_STR],
        ['木曜','delivery_thu',AppConst::TYPE_STR],
        ['金曜','delivery_fri',AppConst::TYPE_STR],
        ['土曜','delivery_sat',AppConst::TYPE_STR],
        ['日曜','delivery_sun',AppConst::TYPE_STR],
        ['祝前','delivery_holi_before',AppConst::TYPE_STR],
        ['祝日','delivery_holi',AppConst::TYPE_STR],
        ['祝後','delivery_holi_after',AppConst::TYPE_STR],
        ['受注日期間・曜日区分','order_date_type',AppConst::TYPE_STR],
        ['日付','order_date',AppConst::TYPE_STR],
        ['期間FROM','order_date_from',AppConst::TYPE_STR],
        ['期間TO','order_date_to',AppConst::TYPE_STR],
        ['月曜','order_mon',AppConst::TYPE_STR],
        ['火曜','order_tue',AppConst::TYPE_STR],
        ['水曜','order_web',AppConst::TYPE_STR],
        ['木曜','order_thu',AppConst::TYPE_STR],
        ['金曜','order_fri',AppConst::TYPE_STR],
        ['土曜','order_sat',AppConst::TYPE_STR],
        ['日曜','order_sun',AppConst::TYPE_STR],
        ['祝前','order_holi_before',AppConst::TYPE_STR],
        ['祝日','order_holi',AppConst::TYPE_STR],
        ['祝後','order_holi_after',AppConst::TYPE_STR],
        ['振替先配送デポCD','trans_depo_cd',AppConst::TYPE_STR],
        ['振替先配送デポ名','trans_depo_name',AppConst::TYPE_STR],
        ['備考','remark',AppConst::TYPE_STR],
    ],
    // デポ稼働日確認
    'calendar' => [
        ['デポCD','depo_cd',AppConst::TYPE_STR],
        ['デポ名','deponame',AppConst::TYPE_STR],
        ['都道府県','pref_name',AppConst::TYPE_STR],
        ['承認区分','approval_cls',AppConst::TYPE_STR],
        ['承認日付','approval_date',AppConst::TYPE_STR],
        ['承認者','approval_name',AppConst::TYPE_STR],
        ['確認区分','confirm_flg',AppConst::TYPE_STR],
        ['1日前日締切','before_deadline_flg1',AppConst::TYPE_STR],
        ['1日当日配送','today_delivery_flg1',AppConst::TYPE_STR],
        ['1日変更理由（デポ）','annotation_depo1',AppConst::TYPE_STR],
        ['1日変更理由（表示）','annotation_disp1',AppConst::TYPE_STR],
        ['2日前日締切','before_deadline_flg2',AppConst::TYPE_STR],
        ['2日当日配送','today_delivery_flg2',AppConst::TYPE_STR],
        ['2日変更理由（デポ）','annotation_depo2',AppConst::TYPE_STR],
        ['2日変更理由（表示）','annotation_disp2',AppConst::TYPE_STR],
        ['3日前日締切','before_deadline_flg3',AppConst::TYPE_STR],
        ['3日当日配送','today_delivery_flg3',AppConst::TYPE_STR],
        ['3日変更理由（デポ）','annotation_depo3',AppConst::TYPE_STR],
        ['3日変更理由（表示）','annotation_disp3',AppConst::TYPE_STR],
        ['4日前日締切','before_deadline_flg4',AppConst::TYPE_STR],
        ['4日当日配送','today_delivery_flg4',AppConst::TYPE_STR],
        ['4日変更理由（デポ）','annotation_depo4',AppConst::TYPE_STR],
        ['4日変更理由（表示）','annotation_disp4',AppConst::TYPE_STR],
        ['5日前日締切','before_deadline_flg5',AppConst::TYPE_STR],
        ['5日当日配送','today_delivery_flg5',AppConst::TYPE_STR],
        ['5日変更理由（デポ）','annotation_depo5',AppConst::TYPE_STR],
        ['5日変更理由（表示）','annotation_disp5',AppConst::TYPE_STR],
        ['6日前日締切','before_deadline_flg6',AppConst::TYPE_STR],
        ['6日当日配送','today_delivery_flg6',AppConst::TYPE_STR],
        ['6日変更理由（デポ）','annotation_depo6',AppConst::TYPE_STR],
        ['6日変更理由（表示）','annotation_disp6',AppConst::TYPE_STR],
        ['7日前日締切','before_deadline_flg7',AppConst::TYPE_STR],
        ['7日当日配送','today_delivery_flg7',AppConst::TYPE_STR],
        ['7日変更理由（デポ）','annotation_depo7',AppConst::TYPE_STR],
        ['7日変更理由（表示）','annotation_disp7',AppConst::TYPE_STR],
        ['8日前日締切','before_deadline_flg8',AppConst::TYPE_STR],
        ['8日当日配送','today_delivery_flg8',AppConst::TYPE_STR],
        ['8日変更理由（デポ）','annotation_depo8',AppConst::TYPE_STR],
        ['8日変更理由（表示）','annotation_disp8',AppConst::TYPE_STR],
        ['9日前日締切','before_deadline_flg9',AppConst::TYPE_STR],
        ['9日当日配送','today_delivery_flg9',AppConst::TYPE_STR],
        ['9日変更理由（デポ）','annotation_depo9',AppConst::TYPE_STR],
        ['9日変更理由（表示）','annotation_disp9',AppConst::TYPE_STR],
        ['10日前日締切','before_deadline_flg10',AppConst::TYPE_STR],
        ['10日当日配送','today_delivery_flg10',AppConst::TYPE_STR],
        ['10日変更理由（デポ）','annotation_depo10',AppConst::TYPE_STR],
        ['10日変更理由（表示）','annotation_disp10',AppConst::TYPE_STR],
        ['11日前日締切','before_deadline_flg11',AppConst::TYPE_STR],
        ['11日当日配送','today_delivery_flg11',AppConst::TYPE_STR],
        ['11日変更理由（デポ）','annotation_depo11',AppConst::TYPE_STR],
        ['11日変更理由（表示）','annotation_disp11',AppConst::TYPE_STR],
        ['12日前日締切','before_deadline_flg12',AppConst::TYPE_STR],
        ['12日当日配送','today_delivery_flg12',AppConst::TYPE_STR],
        ['12日変更理由（デポ）','annotation_depo12',AppConst::TYPE_STR],
        ['12日変更理由（表示）','annotation_disp12',AppConst::TYPE_STR],
        ['13日前日締切','before_deadline_flg13',AppConst::TYPE_STR],
        ['13日当日配送','today_delivery_flg13',AppConst::TYPE_STR],
        ['13日変更理由（デポ）','annotation_depo13',AppConst::TYPE_STR],
        ['13日変更理由（表示）','annotation_disp13',AppConst::TYPE_STR],
        ['14日前日締切','before_deadline_flg14',AppConst::TYPE_STR],
        ['14日当日配送','today_delivery_flg14',AppConst::TYPE_STR],
        ['14日変更理由（デポ）','annotation_depo14',AppConst::TYPE_STR],
        ['14日変更理由（表示）','annotation_disp14',AppConst::TYPE_STR],
        ['15日前日締切','before_deadline_flg15',AppConst::TYPE_STR],
        ['15日当日配送','today_delivery_flg15',AppConst::TYPE_STR],
        ['15日変更理由（デポ）','annotation_depo15',AppConst::TYPE_STR],
        ['15日変更理由（表示）','annotation_disp15',AppConst::TYPE_STR],
        ['16日前日締切','before_deadline_flg16',AppConst::TYPE_STR],
        ['16日当日配送','today_delivery_flg16',AppConst::TYPE_STR],
        ['16日変更理由（デポ）','annotation_depo16',AppConst::TYPE_STR],
        ['16日変更理由（表示）','annotation_disp16',AppConst::TYPE_STR],
        ['17日前日締切','before_deadline_flg17',AppConst::TYPE_STR],
        ['17日当日配送','today_delivery_flg17',AppConst::TYPE_STR],
        ['17日変更理由（デポ）','annotation_depo17',AppConst::TYPE_STR],
        ['17日変更理由（表示）','annotation_disp17',AppConst::TYPE_STR],
        ['18日前日締切','before_deadline_flg18',AppConst::TYPE_STR],
        ['18日当日配送','today_delivery_flg18',AppConst::TYPE_STR],
        ['18日変更理由（デポ）','annotation_depo18',AppConst::TYPE_STR],
        ['18日変更理由（表示）','annotation_disp18',AppConst::TYPE_STR],
        ['19日前日締切','before_deadline_flg19',AppConst::TYPE_STR],
        ['19日当日配送','today_delivery_flg19',AppConst::TYPE_STR],
        ['19日変更理由（デポ）','annotation_depo19',AppConst::TYPE_STR],
        ['19日変更理由（表示）','annotation_disp19',AppConst::TYPE_STR],
        ['20日前日締切','before_deadline_flg20',AppConst::TYPE_STR],
        ['20日当日配送','today_delivery_flg20',AppConst::TYPE_STR],
        ['20日変更理由（デポ）','annotation_depo20',AppConst::TYPE_STR],
        ['20日変更理由（表示）','annotation_disp20',AppConst::TYPE_STR],
        ['21日前日締切','before_deadline_flg21',AppConst::TYPE_STR],
        ['21日当日配送','today_delivery_flg21',AppConst::TYPE_STR],
        ['21日変更理由（デポ）','annotation_depo21',AppConst::TYPE_STR],
        ['21日変更理由（表示）','annotation_disp21',AppConst::TYPE_STR],
        ['22日前日締切','before_deadline_flg22',AppConst::TYPE_STR],
        ['22日当日配送','today_delivery_flg22',AppConst::TYPE_STR],
        ['22日変更理由（デポ）','annotation_depo22',AppConst::TYPE_STR],
        ['22日変更理由（表示）','annotation_disp22',AppConst::TYPE_STR],
        ['23日前日締切','before_deadline_flg23',AppConst::TYPE_STR],
        ['23日当日配送','today_delivery_flg23',AppConst::TYPE_STR],
        ['23日変更理由（デポ）','annotation_depo23',AppConst::TYPE_STR],
        ['23日変更理由（表示）','annotation_disp23',AppConst::TYPE_STR],
        ['24日前日締切','before_deadline_flg24',AppConst::TYPE_STR],
        ['24日当日配送','today_delivery_flg24',AppConst::TYPE_STR],
        ['24日変更理由（デポ）','annotation_depo24',AppConst::TYPE_STR],
        ['24日変更理由（表示）','annotation_disp24',AppConst::TYPE_STR],
        ['25日前日締切','before_deadline_flg25',AppConst::TYPE_STR],
        ['25日当日配送','today_delivery_flg25',AppConst::TYPE_STR],
        ['25日変更理由（デポ）','annotation_depo25',AppConst::TYPE_STR],
        ['25日変更理由（表示）','annotation_disp25',AppConst::TYPE_STR],
        ['26日前日締切','before_deadline_flg26',AppConst::TYPE_STR],
        ['26日当日配送','today_delivery_flg26',AppConst::TYPE_STR],
        ['26日変更理由（デポ）','annotation_depo26',AppConst::TYPE_STR],
        ['26日変更理由（表示）','annotation_disp26',AppConst::TYPE_STR],
        ['27日前日締切','before_deadline_flg27',AppConst::TYPE_STR],
        ['27日当日配送','today_delivery_flg27',AppConst::TYPE_STR],
        ['27日変更理由（デポ）','annotation_depo27',AppConst::TYPE_STR],
        ['27日変更理由（表示）','annotation_disp27',AppConst::TYPE_STR],
        ['28日前日締切','before_deadline_flg28',AppConst::TYPE_STR],
        ['28日当日配送','today_delivery_flg28',AppConst::TYPE_STR],
        ['28日変更理由（デポ）','annotation_depo28',AppConst::TYPE_STR],
        ['28日変更理由（表示）','annotation_disp28',AppConst::TYPE_STR],
        ['29日前日締切','before_deadline_flg29',AppConst::TYPE_STR],
        ['29日当日配送','today_delivery_flg29',AppConst::TYPE_STR],
        ['29日変更理由（デポ）','annotation_depo29',AppConst::TYPE_STR],
        ['29日変更理由（表示）','annotation_disp29',AppConst::TYPE_STR],
        ['30日前日締切','before_deadline_flg30',AppConst::TYPE_STR],
        ['30日当日配送','today_delivery_flg30',AppConst::TYPE_STR],
        ['30日変更理由（デポ）','annotation_depo30',AppConst::TYPE_STR],
        ['30日変更理由（表示）','annotation_disp30',AppConst::TYPE_STR],
        ['31日前日締切','before_deadline_flg31',AppConst::TYPE_STR],
        ['31日当日配送','today_delivery_flg31',AppConst::TYPE_STR],
        ['31日変更理由（デポ）','annotation_depo31',AppConst::TYPE_STR],
        ['31日変更理由（表示）','annotation_disp31',AppConst::TYPE_STR],
    ],
    // リードタイム情報
    'lead_time' => [
        ['デポ名CD','depo_cd',AppConst::TYPE_STR],
        ['デポ名','deponame',AppConst::TYPE_STR],
        ['住所CD','addrcd',AppConst::TYPE_STR],
        ['JIS市区町村','jiscode',AppConst::TYPE_STR],
        ['郵便番号','zip_cd',AppConst::TYPE_STR],
        ['都道府県CD','pref_cd',AppConst::TYPE_STR],
        ['市区郡','siku',AppConst::TYPE_STR],
        ['町名','tyou',AppConst::TYPE_STR],
        ['翌日時間指定','next_day_time_type',AppConst::TYPE_STR],
        ['エリア当日配送可否','is_area_today_delivery_flg',AppConst::TYPE_STR],
        ['翌日配送締切時間','next_day_time_deadline',AppConst::TYPE_STR],
        ['当日配送締切時間１','today_time_deadline1',AppConst::TYPE_STR],
        ['当日配送締切時間２','today_time_deadline2',AppConst::TYPE_STR],
    ],
    // デポ商品紐付情報
    'depo_item' => [
        ['デポCD','depo_cd',AppConst::TYPE_STR],
        ['デポ名','deponame',AppConst::TYPE_STR],
        ['商品CD','item_cd',AppConst::TYPE_STR],
        ['商品名','item_name',AppConst::TYPE_STR],
    ],
    // デポ住所紐付情報
    'depo_address' => [
        ['デポCD','depo_cd',AppConst::TYPE_STR],
        ['デポ名','deponame',AppConst::TYPE_STR],
        ['JIS市区町村','jiscode',AppConst::TYPE_STR],
        ['郵便番号','zip_cd',AppConst::TYPE_STR],
        ['都道府県CD','pref_cd',AppConst::TYPE_STR],
        ['市区郡','siku',AppConst::TYPE_STR],
        ['町名','tyou',AppConst::TYPE_STR],
    ],
    // C_LI_03_受注データ更新用CSV出力クラス
    'chg_depo_info' => [
        ['デポCD','depoCd',AppConst::NUM],
        ['都道府県CD','prefCd',AppConst::NUM],
        ['市区郡','siku',AppConst::TYPE_STR],
        ['町名','tyou',AppConst::TYPE_STR],
        ['商品CD','itemCd',AppConst::NUM],
        ['期間FROM','ymdFrom',AppConst::TYPE_STR],
        ['期間TO','ymdTo',AppConst::TYPE_STR],
    ],

];
