version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    container_name: web
    volumes:
      - .:/var/www/s_leadtime
    ports:
      - 8081:80
      - 443:443
    depends_on:
      - php-laravel
    mem_limit: 1g

  php-laravel:
    build:
      context: .
      dockerfile: ./docker/php-laravel/Dockerfile
    container_name: php-laravel
    volumes:
      - .:/var/www/s_leadtime
      - ./docker/php-laravel/xdebug.ini:/usr/local/etc/php/php.ini
    links:
      - postgres
    depends_on:
      - postgres
    mem_limit: 6g

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - test_db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root
    mem_limit: 2g

  pgadmin4:
    build:
      context: .
      dockerfile: ./docker/pgadmin4/Dockerfile
    container_name: pgadmin4
    ports:
      - 8082:80
    volumes:
      - ./docker/pgadmin4/data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    restart: always
    mem_limit: 1g

volumes:
  test_db:
    external: true